-- MySQL Script generated by MySQL Workbench
-- Thu Jul  4 12:34:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema web_ecom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web_ecom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web_ecom` DEFAULT CHARACTER SET utf8 ;
USE `web_ecom` ;

-- -----------------------------------------------------
-- Table `web_ecom`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_ecom`.`Customer` (
  `id` INT NOT NULL,
  `fname` VARCHAR(60) NOT NULL,
  `lname` VARCHAR(60) NOT NULL,
  `phone_number` VARCHAR(28) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_ecom`.`customer_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_ecom`.`customer_address` (
  `id` INT NOT NULL,
  `customer` INT NOT NULL,
  `addl1` VARCHAR(300) NOT NULL,
  `addl2` VARCHAR(300) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `current` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `customer_idx` (`customer` ASC),
  CONSTRAINT `customer`
    FOREIGN KEY (`customer`)
    REFERENCES `web_ecom`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_ecom`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_ecom`.`supplier` (
  `id` INT NOT NULL,
  `name` VARCHAR(300) NOT NULL,
  `adress` VARCHAR(450) NOT NULL,
  `phonenum` VARCHAR(28) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_ecom`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_ecom`.`item` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `selPrice` INT NOT NULL,
  `buyPrice` INT NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `web_ecom`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_ecom`.`invoice` (
  `id` INT NOT NULL,
  `invoice_item` INT NOT NULL,
  `quantity` INT NOT NULL,
  `issued` DATE NOT NULL,
  `billed` DATE NOT NULL,
  `invoice_val` INT NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `invoice_item_idx` (`invoice_item` ASC),
  CONSTRAINT `invoice_item`
    FOREIGN KEY (`invoice_item`)
    REFERENCES `web_ecom`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_ecom`.`sysuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_ecom`.`sysuser` (
  `id` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_ecom`.`cus_cachier_invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_ecom`.`cus_cachier_invoice` (
  `id` INT NOT NULL,
  `cus` INT NOT NULL,
  `sysuser` INT NOT NULL,
  `invoice` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `customer_idx` (`cus` ASC),
  INDEX `invoice_idx` (`invoice` ASC),
  INDEX `user_idx` (`sysuser` ASC),
  CONSTRAINT `cus`
    FOREIGN KEY (`cus`)
    REFERENCES `web_ecom`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `invoice`
    FOREIGN KEY (`invoice`)
    REFERENCES `web_ecom`.`invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sysuser`
    FOREIGN KEY (`sysuser`)
    REFERENCES `web_ecom`.`sysuser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web_ecom`.`grn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_ecom`.`grn` (
  `id` INT NOT NULL,
  `grn_item` INT NOT NULL,
  `quantity` INT NOT NULL,
  `received` DATE NOT NULL,
  `payed` DATE NOT NULL,
  `grn_total` INT NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `item_idx` (`grn_item` ASC),
  CONSTRAINT `grn_item`
    FOREIGN KEY (`grn_item`)
    REFERENCES `web_ecom`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `web_ecom`.`sup_grn_skeeper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_ecom`.`sup_grn_skeeper` (
  `id` INT NOT NULL,
  `sup` INT NOT NULL,
  `grn` INT NOT NULL,
  `skeeper` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sup_idx` (`sup` ASC),
  INDEX `grn_idx` (`grn` ASC),
  INDEX `skeeper_idx` (`skeeper` ASC),
  CONSTRAINT `sup`
    FOREIGN KEY (`sup`)
    REFERENCES `web_ecom`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `skeeper`
    FOREIGN KEY (`skeeper`)
    REFERENCES `web_ecom`.`sysuser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grn`
    FOREIGN KEY (`grn`)
    REFERENCES `web_ecom`.`grn` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
